### PR TITLE
Add subscription client documentation

### PR DESCRIPTION
**Pull request by Sen-Com**
@ironman0x7b2, @bsrinivas8687 
PR for #45.
Added documentation for the client side of the subscription module. Each featured message includes a short description, intended usage, available flags and an example.

### CODE REVIEW

**Comment by Sen-Com** [comment]
See #45.

**Comment by Sen-Com** [comment]
Hello?

**Comment by bsrinivas8687** [comment]
Hi @Sen-Com Thank you for the contributions. This documentation should be under [docs repostiory](https://github.com/sentinel-official/docs/tree/master/modules)

**Comment by Sen-Com** [comment]
Done, @bsrinivas8687! See [here](@bsrinivas8687).

**Pull request closed without merging**
