### PR TITLE
add keeper and genesis tests for provider module(#36)

### PR DESCRIPTION
**Pull request by Raneet10**
### Description

References #36

### CODE REVIEW

**Comment by bsrinivas8687** [comment]
Hi @Raneet10, Thank you for your contribution. This PR is blocked by PR #70

**Comment by Raneet10** [comment]
> Hi @Raneet10, Thank you for your contribution. This PR is blocked by PR #70

**Comment by Raneet10** [comment]
Thanks @bsrinivas8687 ! I guess I should have created the PR against `dep_upgrade` branch ? Should I do the same and close this one ?

**Comment by bsrinivas8687** [comment]
> Thanks @bsrinivas8687 ! I guess I should have created the PR against `dep_upgrade` branch ? Should I do the same and close this one ?

Yes, you can do that

**Comment by Raneet10** [comment]
Hey @bsrinivas8687 can you help resolve the conflicts ?

**Comment by Raneet10** [comment]
Hi @bsrinivas8687 any updates on this PR? Is there something missing in the tests?

**Pull request closed without merging**
